server.port: 9090
logging:
  level:
    root: INFO
spring:
  graphql:
    schema:
      file-extensions:
        - .graphql
    cors:
      allowed-origins: '*'
      allowed-methods: '*'
    graphiql:
      enabled: true

